# Generated by Django 4.2.7 on 2023-11-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0002_classmate_address_classmate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1),
        ),
    ]
